Import fix
Error message caused by vanilla linkify:
>>> import markdown
>>> markdown.markdown('http://example.org/', ['linkify'])
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\pyzo2013c\lib\site-packages\markdown\__init__.py", line 410, in markdown
    md = Markdown(*args, **kwargs)
  File "C:\pyzo2013c\lib\site-packages\markdown\__init__.py", line 137, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "C:\pyzo2013c\lib\site-packages\markdown\__init__.py", line 163, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, []))
  File "C:\pyzo2013c\lib\site-packages\markdown\__init__.py", line 201, in build_extension
    module = __import__(module_name_old_style)
  File "C:\pyzo2013c\lib\site-packages\mdx_linkify\__init__.py", line 1, in <module>
    from mdx_linkify import makeExtension
ImportError: cannot import name makeExtension